// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobs

import (
	"context"

	"github.com/rodruizronald/tw-backend/internal/jobtech"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataRepository creates a new instance of MockDataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataRepository {
	mock := &MockDataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataRepository is an autogenerated mock type for the DataRepository type
type MockDataRepository struct {
	mock.Mock
}

type MockDataRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataRepository) EXPECT() *MockDataRepository_Expecter {
	return &MockDataRepository_Expecter{mock: &_m.Mock}
}

// GetJobTechnologiesBatch provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) GetJobTechnologiesBatch(ctx context.Context, jobIDs []int) (map[int][]*jobtech.JobTechnologyWithDetails, error) {
	ret := _mock.Called(ctx, jobIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetJobTechnologiesBatch")
	}

	var r0 map[int][]*jobtech.JobTechnologyWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) (map[int][]*jobtech.JobTechnologyWithDetails, error)); ok {
		return returnFunc(ctx, jobIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) map[int][]*jobtech.JobTechnologyWithDetails); ok {
		r0 = returnFunc(ctx, jobIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int][]*jobtech.JobTechnologyWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, jobIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataRepository_GetJobTechnologiesBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobTechnologiesBatch'
type MockDataRepository_GetJobTechnologiesBatch_Call struct {
	*mock.Call
}

// GetJobTechnologiesBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - jobIDs []int
func (_e *MockDataRepository_Expecter) GetJobTechnologiesBatch(ctx interface{}, jobIDs interface{}) *MockDataRepository_GetJobTechnologiesBatch_Call {
	return &MockDataRepository_GetJobTechnologiesBatch_Call{Call: _e.mock.On("GetJobTechnologiesBatch", ctx, jobIDs)}
}

func (_c *MockDataRepository_GetJobTechnologiesBatch_Call) Run(run func(ctx context.Context, jobIDs []int)) *MockDataRepository_GetJobTechnologiesBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_GetJobTechnologiesBatch_Call) Return(intToJobTechnologyWithDetailss map[int][]*jobtech.JobTechnologyWithDetails, err error) *MockDataRepository_GetJobTechnologiesBatch_Call {
	_c.Call.Return(intToJobTechnologyWithDetailss, err)
	return _c
}

func (_c *MockDataRepository_GetJobTechnologiesBatch_Call) RunAndReturn(run func(ctx context.Context, jobIDs []int) (map[int][]*jobtech.JobTechnologyWithDetails, error)) *MockDataRepository_GetJobTechnologiesBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchCount provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) GetSearchCount(ctx context.Context, params *SearchParams) (int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SearchParams) (int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SearchParams) int); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *SearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataRepository_GetSearchCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchCount'
type MockDataRepository_GetSearchCount_Call struct {
	*mock.Call
}

// GetSearchCount is a helper method to define mock.On call
//   - ctx context.Context
//   - params *SearchParams
func (_e *MockDataRepository_Expecter) GetSearchCount(ctx interface{}, params interface{}) *MockDataRepository_GetSearchCount_Call {
	return &MockDataRepository_GetSearchCount_Call{Call: _e.mock.On("GetSearchCount", ctx, params)}
}

func (_c *MockDataRepository_GetSearchCount_Call) Run(run func(ctx context.Context, params *SearchParams)) *MockDataRepository_GetSearchCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SearchParams
		if args[1] != nil {
			arg1 = args[1].(*SearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_GetSearchCount_Call) Return(n int, err error) *MockDataRepository_GetSearchCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDataRepository_GetSearchCount_Call) RunAndReturn(run func(ctx context.Context, params *SearchParams) (int, error)) *MockDataRepository_GetSearchCount_Call {
	_c.Call.Return(run)
	return _c
}

// SearchJobsWithCount provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) SearchJobsWithCount(ctx context.Context, params *SearchParams) ([]*JobWithCompany, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchJobsWithCount")
	}

	var r0 []*JobWithCompany
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SearchParams) ([]*JobWithCompany, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SearchParams) []*JobWithCompany); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*JobWithCompany)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *SearchParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *SearchParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDataRepository_SearchJobsWithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchJobsWithCount'
type MockDataRepository_SearchJobsWithCount_Call struct {
	*mock.Call
}

// SearchJobsWithCount is a helper method to define mock.On call
//   - ctx context.Context
//   - params *SearchParams
func (_e *MockDataRepository_Expecter) SearchJobsWithCount(ctx interface{}, params interface{}) *MockDataRepository_SearchJobsWithCount_Call {
	return &MockDataRepository_SearchJobsWithCount_Call{Call: _e.mock.On("SearchJobsWithCount", ctx, params)}
}

func (_c *MockDataRepository_SearchJobsWithCount_Call) Run(run func(ctx context.Context, params *SearchParams)) *MockDataRepository_SearchJobsWithCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SearchParams
		if args[1] != nil {
			arg1 = args[1].(*SearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_SearchJobsWithCount_Call) Return(jobWithCompanys []*JobWithCompany, n int, err error) *MockDataRepository_SearchJobsWithCount_Call {
	_c.Call.Return(jobWithCompanys, n, err)
	return _c
}

func (_c *MockDataRepository_SearchJobsWithCount_Call) RunAndReturn(run func(ctx context.Context, params *SearchParams) ([]*JobWithCompany, int, error)) *MockDataRepository_SearchJobsWithCount_Call {
	_c.Call.Return(run)
	return _c
}
